---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: assembleDebug
  image: circleci/android:api-28
  commands:
  - chmod +x ./gradlew
  - ./gradlew assembleDebug

- name: lintDebug
  image: circleci/android:api-28
  commands:
  - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint

- name: debugTests
  image: circleci/android:api-28
  commands:
  - ./gradlew -Pci --console=plain :app:testDebug
