---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: assembleDebug
  image: circleci/android:api-28
  commands:
  - sudo chmod 777 -R /drone/src
  - sudo chmod +x ./gradlew
  - ./gradlew androidDependencies
  - ./gradlew assembleDebug

- name: lintDebug
  image: circleci/android:api-28
  commands:
  - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint

- name: debugTests
  image: circleci/android:api-28
  commands:
  - ./gradlew -Pci --console=plain :app:testDebug
